services:
  docs:
    image: harjs-design
    container_name: harjs-design
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REPO: https://github.com/kaancetin-f/harjs-design-react-ui.git
        BRANCH: main
    ports:
      - "3000:3000"
    restart: unless-stopped
