name: Compatibility

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment:
          - next-pages
          - vite
          - cra5
          - remix
          - blitz

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run test:compat -- ${{ matrix.environment }}
